# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pzhsljnAUv8gtnZ5m30aGvhuXUb7YaGn
"""

# ============================================================
#   EXCEL DASHBOARD PRO — Aplicación Ejecutiva de Métricas
#   Desarrollado con Python + Streamlit
#   Autor: Generado para JUAN JOSE MOLINA OCAMPO
# ============================================================

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from io import BytesIO

# ─────────────────────────────────────────────
#  CONFIGURACIÓN GENERAL DE LA PÁGINA
# ─────────────────────────────────────────────
st.set_page_config(
    page_title="Excel Dashboard Pro",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ─────────────────────────────────────────────
#  ESTILOS CSS EJECUTIVOS
# ─────────────────────────────────────────────
st.markdown("""
    <style>
        /* Fondo general */
        .stApp { background-color: #0f1117; }

        /* Títulos */
        h1, h2, h3 { color: #FFFFFF !important; }

        /* Tarjetas KPI */
        .kpi-card {
            background: linear-gradient(135deg, #1e2130, #252840);
            border-left: 4px solid #4f8ef7;
            border-radius: 12px;
            padding: 20px;
            margin: 8px 0;
            box-shadow: 0 4px 15px rgba(79,142,247,0.15);
        }
        .kpi-title {
            color: #8892a4;
            font-size: 13px;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        .kpi-value {
            color: #FFFFFF;
            font-size: 32px;
            font-weight: 800;
            margin: 4px 0;
        }
        .kpi-sub {
            color: #4f8ef7;
            font-size: 12px;
        }

        /* Sidebar */
        .css-1d391kg { background-color: #1a1d2e !important; }

        /* Botones */
        .stButton > button {
            background: linear-gradient(90deg, #4f8ef7, #7c4dff);
            color: white;
            border: none;
            border-radius: 8px;
            padding: 10px 24px;
            font-weight: 600;
            width: 100%;
        }

        /* Separador */
        hr { border-color: #2d3147 !important; }

        /* Encabezado superior */
        .top-header {
            background: linear-gradient(90deg, #1a1d2e, #252840);
            padding: 20px 30px;
            border-radius: 16px;
            border-left: 5px solid #4f8ef7;
            margin-bottom: 24px;
        }
    </style>
""", unsafe_allow_html=True)


# ─────────────────────────────────────────────
#  ENCABEZADO PRINCIPAL
# ─────────────────────────────────────────────
st.markdown("""
    <div class="top-header">
        <h1 style='margin:0; font-size:28px;'>📊 Excel Dashboard Pro</h1>
        <p style='color:#8892a4; margin:6px 0 0 0; font-size:14px;'>
            Sube tu archivo Excel y obtén análisis ejecutivo instantáneo · Personal Administrativo
        </p>
    </div>
""", unsafe_allow_html=True)


# ─────────────────────────────────────────────
#  SIDEBAR — CARGA DE ARCHIVO Y FILTROS
# ─────────────────────────────────────────────
with st.sidebar:
    st.markdown("## 📂 Cargar Datos")
    uploaded_file = st.file_uploader(
        "Sube tu archivo Excel",
        type=["xlsx", "xls"],
        help="Formatos soportados: .xlsx, .xls"
    )
    st.markdown("---")
    st.markdown("### ⚙️ Configuración")
    mostrar_tabla = st.checkbox("Mostrar tabla de datos", value=True)
    mostrar_correlacion = st.checkbox("Mostrar mapa de correlación", value=True)
    mostrar_distribucion = st.checkbox("Mostrar distribuciones", value=True)
    st.markdown("---")
    st.markdown("""
        <div style='color:#8892a4; font-size:11px; text-align:center;'>
            Excel Dashboard Pro v1.0<br>
            Powered by Streamlit & Plotly
        </div>
    """, unsafe_allow_html=True)


# ─────────────────────────────────────────────
#  FUNCIONES AUXILIARES
# ─────────────────────────────────────────────
@st.cache_data
def cargar_excel(file):
    return pd.read_excel(file)

def formato_numero(n):
    if abs(n) >= 1_000_000:
        return f"{n/1_000_000:.2f}M"
    elif abs(n) >= 1_000:
        return f"{n/1_000:.1f}K"
    return f"{n:,.2f}"

def render_kpi(titulo, valor, subtitulo="", color="#4f8ef7"):
    st.markdown(f"""
        <div class="kpi-card" style="border-left-color:{color};">
            <div class="kpi-title">{titulo}</div>
            <div class="kpi-value">{valor}</div>
            <div class="kpi-sub">{subtitulo}</div>
        </div>
    """, unsafe_allow_html=True)

COLORES_EJECUTIVOS = [
    "#4f8ef7", "#7c4dff", "#00e5a0", "#ff6b6b",
    "#ffa94d", "#38d9f5", "#f06595", "#74c0fc"
]


# ─────────────────────────────────────────────
#  PANTALLA INICIAL (SIN ARCHIVO)
# ─────────────────────────────────────────────
if uploaded_file is None:
    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        st.markdown("""
            <div style='
                text-align:center;
                padding: 60px 40px;
                background: linear-gradient(135deg, #1e2130, #252840);
                border-radius: 20px;
                border: 2px dashed #2d3147;
                margin-top: 40px;
            '>
                <div style='font-size:72px;'>📊</div>
                <h2 style='color:#FFFFFF; margin:20px 0 10px;'>Sube tu archivo Excel</h2>
                <p style='color:#8892a4; font-size:15px;'>
                    Carga cualquier archivo .xlsx o .xls desde el panel izquierdo<br>
                    y obtén un dashboard ejecutivo de forma instantánea.
                </p>
                <div style='margin-top:30px; color:#4f8ef7; font-size:13px;'>
                    ✅ KPIs automáticos &nbsp;|&nbsp;
                    📈 Gráficas interactivas &nbsp;|&nbsp;
                    🔍 Análisis inteligente
                </div>
            </div>
        """, unsafe_allow_html=True)
    st.stop()


# ─────────────────────────────────────────────
#  CARGA Y PROCESAMIENTO DEL ARCHIVO
# ─────────────────────────────────────────────
try:
    df = cargar_excel(uploaded_file)
except Exception as e:
    st.error(f"❌ Error al leer el archivo: {e}")
    st.stop()

# Detección de columnas
col_numericas = df.select_dtypes(include=np.number).columns.tolist()
col_categoricas = df.select_dtypes(include=['object', 'category']).columns.tolist()
col_fechas = df.select_dtypes(include=['datetime64']).columns.tolist()

# Intentar detectar fechas en texto
for col in col_categoricas.copy():
    try:
        df[col] = pd.to_datetime(df[col])
        col_fechas.append(col)
        col_categoricas.remove(col)
    except:
        pass


# ─────────────────────────────────────────────
#  FILTROS EN SIDEBAR (dinámicos)
# ─────────────────────────────────────────────
with st.sidebar:
    st.markdown("### 🔍 Filtros")
    df_filtrado = df.copy()

    for col in col_categoricas[:3]:  # máx. 3 filtros categóricos
        opciones = ["Todos"] + sorted(df[col].dropna().unique().tolist(), key=lambda x: str(x))
        seleccion = st.selectbox(f"Filtrar por **{col}**", opciones)
        if seleccion != "Todos":
            df_filtrado = df_filtrado[df_filtrado[col] == seleccion]

    if col_numericas:
        col_rango = col_numericas[0]
        min_val = float(df[col_rango].min())
        max_val = float(df[col_rango].max())
        if min_val < max_val:
            rango = st.slider(
                f"Rango: **{col_rango}**",
                min_value=min_val,
                max_value=max_val,
                value=(min_val, max_val)
            )
            df_filtrado = df_filtrado[
                df_filtrado[col_rango].between(rango[0], rango[1])
            ]


# ─────────────────────────────────────────────
#  BANNER DE RESUMEN DEL ARCHIVO
# ─────────────────────────────────────────────
st.markdown(f"""
    <div style='
        background: linear-gradient(135deg, #1a2744, #1e2130);
        border-radius:12px; padding:16px 24px;
        display:flex; gap:30px; margin-bottom:20px;
        border: 1px solid #2d3147;
    '>
        <span style='color:#8892a4; font-size:13px;'>
            📁 <b style='color:#fff;'>{uploaded_file.name}</b>
        </span>
        <span style='color:#8892a4; font-size:13px;'>
            🗂️ <b style='color:#4f8ef7;'>{df_filtrado.shape[0]:,}</b> filas ·
            <b style='color:#4f8ef7;'>{df_filtrado.shape[1]}</b> columnas
        </span>
        <span style='color:#8892a4; font-size:13px;'>
            🔢 <b style='color:#00e5a0;'>{len(col_numericas)}</b> numéricas ·
            🏷️ <b style='color:#ffa94d;'>{len(col_categoricas)}</b> categóricas
        </span>
    </div>
""", unsafe_allow_html=True)


# ─────────────────────────────────────────────
#  SECCIÓN 1: KPIs EJECUTIVOS
# ─────────────────────────────────────────────
st.markdown("## 📌 Indicadores Clave (KPIs)")
kpi_cols = st.columns(min(len(col_numericas), 4))
colores_kpi = ["#4f8ef7", "#7c4dff", "#00e5a0", "#ff6b6b"]

for i, col in enumerate(col_numericas[:4]):
    with kpi_cols[i]:
        total = df_filtrado[col].sum()
        promedio = df_filtrado[col].mean()
        render_kpi(
            titulo=col.upper(),
            valor=formato_numero(total),
            subtitulo=f"Promedio: {formato_numero(promedio)}",
            color=colores_kpi[i % len(colores_kpi)]
        )

# KPIs adicionales: registros, nulos, categorías únicas
st.markdown("")
meta_cols = st.columns(4)
with meta_cols[0]:
    render_kpi("Total Registros", f"{len(df_filtrado):,}", "filas en el dataset", "#38d9f5")
with meta_cols[1]:
    nulos = df_filtrado.isnull().sum().sum()
    render_kpi("Valores Nulos", f"{nulos:,}", "campos vacíos detectados", "#ffa94d")
with meta_cols[2]:
    render_kpi("Columnas", f"{df_filtrado.shape[1]}", "variables en el dataset", "#f06595")
with meta_cols[3]:
    completitud = round((1 - df_filtrado.isnull().mean().mean()) * 100, 1)
    render_kpi("Completitud", f"{completitud}%", "datos completos", "#00e5a0")


st.markdown("---")


# ─────────────────────────────────────────────
#  SECCIÓN 2: GRÁFICAS PRINCIPALES
# ─────────────────────────────────────────────
st.markdown("## 📈 Visualizaciones Ejecutivas")

if col_numericas and col_categoricas:
    tab1, tab2, tab3, tab4 = st.tabs([
        "📊 Barras", "🥧 Pastel", "📉 Líneas", "🔵 Dispersión"
    ])

    with tab1:
        c1, c2 = st.columns(2)
        with c1:
            eje_x = st.selectbox("Eje X (Categoría)", col_categoricas, key="bar_x")
        with c2:
            eje_y = st.selectbox("Eje Y (Métrica)", col_numericas, key="bar_y")

        df_bar = df_filtrado.groupby(eje_x)[eje_y].sum().reset_index().sort_values(eje_y, ascending=False)
        fig_bar = px.bar(
            df_bar, x=eje_x, y=eje_y,
            color=eje_x,
            color_discrete_sequence=COLORES_EJECUTIVOS,
            title=f"Total de <b>{eje_y}</b> por <b>{eje_x}</b>",
            template="plotly_dark",
            text_auto=True
        )
        fig_bar.update_layout(
            plot_bgcolor="#1e2130", paper_bgcolor="#1e2130",
            font_color="#FFFFFF", showlegend=False,
            title_font_size=16
        )
        st.plotly_chart(fig_bar, use_container_width=True)

    with tab2:
        c1, c2 = st.columns(2)
        with c1:
            pie_cat = st.selectbox("Categoría", col_categoricas, key="pie_cat")
        with c2:
            pie_val = st.selectbox("Valor", col_numericas, key="pie_val")

        df_pie = df_filtrado.groupby(pie_cat)[pie_val].sum().reset_index()
        fig_pie = px.pie(
            df_pie, names=pie_cat, values=pie_val,
            color_discrete_sequence=COLORES_EJECUTIVOS,
            title=f"Distribución de <b>{pie_val}</b> por <b>{pie_cat}</b>",
            template="plotly_dark",
            hole=0.45
        )
        fig_pie.update_layout(
            plot_bgcolor="#1e2130", paper_bgcolor="#1e2130",
            font_color="#FFFFFF", title_font_size=16
        )
        st.plotly_chart(fig_pie, use_container_width=True)

    with tab3:
        c1, c2 = st.columns(2)
        with c1:
            lin_x = st.selectbox("Eje X", col_categoricas + col_fechas, key="lin_x")
        with c2:
            lin_y = st.multiselect("Métricas (Y)", col_numericas, default=col_numericas[:2], key="lin_y")

        if lin_y:
            df_lin = df_filtrado.groupby(lin_x)[lin_y].sum().reset_index()
            fig_lin = px.line(
                df_lin, x=lin_x, y=lin_y,
                color_discrete_sequence=COLORES_EJECUTIVOS,
                title=f"Tendencia de métricas por <b>{lin_x}</b>",
                template="plotly_dark",
                markers=True
            )
            fig_lin.update_layout(
                plot_bgcolor="#1e2130", paper_bgcolor="#1e2130",
                font_color="#FFFFFF", title_font_size=16
            )
            st.plotly_chart(fig_lin, use_container_width=True)

    with tab4:
        if len(col_numericas) >= 2:
            c1, c2, c3 = st.columns(3)
            with c1:
                sc_x = st.selectbox("Eje X", col_numericas, key="sc_x")
            with c2:
                sc_y = st.selectbox("Eje Y", col_numericas, index=1, key="sc_y")
            with c3:
                sc_color = st.selectbox("Color por", col_categoricas, key="sc_color") if col_categoricas else None

            fig_sc = px.scatter(
                df_filtrado, x=sc_x, y=sc_y,
                color=sc_color,
                color_discrete_sequence=COLORES_EJECUTIVOS,
                title=f"Dispersión: <b>{sc_x}</b> vs <b>{sc_y}</b>",
                template="plotly_dark",
                size_max=15,
                opacity=0.8
            )
            fig_sc.update_layout(
                plot_bgcolor="#1e2130", paper_bgcolor="#1e2130",
                font_color="#FFFFFF", title_font_size=16
            )
            st.plotly_chart(fig_sc, use_container_width=True)
        else:
            st.info("Se necesitan al menos 2 columnas numéricas para el gráfico de dispersión.")

elif col_numericas:
    st.info("ℹ️ No se detectaron columnas categóricas. Mostrando histogramas numéricos.")
    cols_g = st.columns(2)
    for i, col in enumerate(col_numericas[:4]):
        with cols_g[i % 2]:
            fig_h = px.histogram(
                df_filtrado, x=col,
                color_discrete_sequence=[COLORES_EJECUTIVOS[i % len(COLORES_EJECUTIVOS)]],
                title=f"Distribución de <b>{col}</b>",
                template="plotly_dark"
            )
            fig_h.update_layout(
                plot_bgcolor="#1e2130", paper_bgcolor="#1e2130",
                font_color="#FFFFFF"
            )
            st.plotly_chart(fig_h, use_container_width=True)

st.markdown("---")


# ─────────────────────────────────────────────
#  SECCIÓN 3: MAPA DE CORRELACIÓN
# ─────────────────────────────────────────────
if mostrar_correlacion and len(col_numericas) >= 2:
    st.markdown("## 🔥 Mapa de Calor — Correlación entre Variables")
    corr = df_filtrado[col_numericas].corr()

    fig_corr, ax = plt.subplots(figsize=(max(6, len(col_numericas)), max(4, len(col_numericas) - 1)))
    fig_corr.patch.set_facecolor("#1e2130")
    ax.set_facecolor("#1e2130")

    sns.heatmap(
        corr, annot=True, fmt=".2f",
        cmap="coolwarm", linewidths=0.5,
        linecolor="#0f1117",
        vmin=-1, vmax=1,
        ax=ax,
        annot_kws={"size": 10, "color": "white"}
    )
    ax.set_title("Correlación entre variables numéricas", color="white", pad=15, fontsize=14)
    ax.tick_params(colors="white")
    plt.xticks(rotation=45, ha="right", color="white")
    plt.yticks(color="white")
    st.pyplot(fig_corr)
    plt.close()
    st.markdown("---")


# ─────────────────────────────────────────────
#  SECCIÓN 4: DISTRIBUCIONES
# ─────────────────────────────────────────────
if mostrar_distribucion and col_numericas:
    st.markdown("## 📐 Distribución por Variable Numérica")
    dist_col = st.selectbox("Selecciona variable", col_numericas, key="dist_col")

    col_a, col_b = st.columns(2)
    with col_a:
        fig_hist = px.histogram(
            df_filtrado, x=dist_col,
            nbins=30,
            color_discrete_sequence=["#4f8ef7"],
            title=f"Histograma de <b>{dist_col}</b>",
            template="plotly_dark",
            marginal="box"
        )
        fig_hist.update_layout(
            plot_bgcolor="#1e2130", paper_bgcolor="#1e2130",
            font_color="#FFFFFF"
        )
        st.plotly_chart(fig_hist, use_container_width=True)

    with col_b:
        fig_box = px.box(
            df_filtrado, y=dist_col,
            color_discrete_sequence=["#7c4dff"],
            title=f"Box Plot de <b>{dist_col}</b>",
            template="plotly_dark",
            points="all"
        )
        fig_box.update_layout(
            plot_bgcolor="#1e2130", paper_bgcolor="#1e2130",
            font_color="#FFFFFF"
        )
        st.plotly_chart(fig_box, use_container_width=True)

    st.markdown("---")


# ─────────────────────────────────────────────
#  SECCIÓN 5: ANÁLISIS AUTOMÁTICO INTELIGENTE
# ─────────────────────────────────────────────
st.markdown("## 🤖 Análisis Automático de los Datos")

insights = []

if col_numericas:
    for col in col_numericas[:4]:
        s = df_filtrado[col].dropna()
        if len(s) == 0:
            continue
        skew = s.skew()
        if skew > 1:
            insights.append(f"📈 **{col}**: distribución sesgada a la derecha (asimetría={skew:.2f}). Hay valores extremos altos.")
        elif skew < -1:
            insights.append(f"📉 **{col}**: distribución sesgada a la izquierda (asimetría={skew:.2f}). Hay valores extremos bajos.")
        else:
            insights.append(f"✅ **{col}**: distribución simétrica (asimetría={skew:.2f}). Datos bien distribuidos.")

        cv = (s.std() / s.mean() * 100) if s.mean() != 0 else 0
        if cv > 50:
            insights.append(f"⚠️ **{col}**: alta variabilidad (CV={cv:.1f}%). Los datos son muy dispersos.")
        else:
            insights.append(f"📊 **{col}**: variabilidad controlada (CV={cv:.1f}%).")

if col_numericas and len(col_numericas) >= 2:
    corr_matrix = df_filtrado[col_numericas].corr()
    for i in range(len(col_numericas)):
        for j in range(i + 1, len(col_numericas)):
            val = corr_matrix.iloc[i, j]
            c1_name = col_numericas[i]
            c2_name = col_numericas[j]
            if abs(val) > 0.8:
                tipo = "positiva fuerte" if val > 0 else "negativa fuerte"
                insights.append(f"🔗 **{c1_name}** y **{c2_name}** tienen correlación {tipo} ({val:.2f}).")

nulos_por_col = df_filtrado.isnull().sum()
cols_con_nulos = nulos_por_col[nulos_por_col > 0]
if len(cols_con_nulos) > 0:
    for col, n in cols_con_nulos.items():
        pct = round(n / len(df_filtrado) * 100, 1)
        insights.append(f"⚠️ **{col}** tiene {n} valores nulos ({pct}% del total).")
else:
    insights.append("✅ El dataset **no tiene valores nulos**. Datos completos.")

# Mostrar insights en tarjetas
col_ins1, col_ins2 = st.columns(2)
for idx, insight in enumerate(insights):
    with (col_ins1 if idx % 2 == 0 else col_ins2):
        st.markdown(f"""
            <div style='
                background:#1e2130;
                border-left:3px solid #4f8ef7;
                border-radius:8px;
                padding:12px 16px;
                margin:6px 0;
                font-size:13px;
                color:#c8d0e0;
            '>{insight}</div>
        """, unsafe_allow_html=True)

st.markdown("---")


# ─────────────────────────────────────────────
#  SECCIÓN 6: TABLA DE DATOS
# ─────────────────────────────────────────────
if mostrar_tabla:
    st.markdown("## 🗃️ Tabla de Datos")
    c1, c2 = st.columns([3, 1])
    with c1:
        busqueda = st.text_input("🔎 Buscar en los datos", placeholder="Escribe para filtrar...")
    with c2:
        n_filas = st.selectbox("Filas a mostrar", [10, 25, 50, 100, "Todas"], index=1)

    df_tabla = df_filtrado.copy()
    if busqueda:
        mask = df_tabla.astype(str).apply(lambda x: x.str.contains(busqueda, case=False)).any(axis=1)
        df_tabla = df_tabla[mask]

    if n_filas != "Todas":
        df_tabla = df_tabla.head(int(n_filas))

    st.dataframe(
        df_tabla,
        use_container_width=True,
        height=350
    )

    # Estadísticas descriptivas
    with st.expander("📊 Ver estadísticas descriptivas"):
        st.dataframe(df_filtrado[col_numericas].describe().round(2), use_container_width=True)

    st.markdown("---")


# ─────────────────────────────────────────────
#  SECCIÓN 7: EXPORTAR DATOS PROCESADOS
# ─────────────────────────────────────────────
st.markdown("## 💾 Exportar Datos Filtrados")
col_exp1, col_exp2 = st.columns(2)

with col_exp1:
    csv_data = df_filtrado.to_csv(index=False).encode("utf-8")
    st.download_button(
        label="⬇️ Descargar como CSV",
        data=csv_data,
        file_name="dashboard_export.csv",
        mime="text/csv"
    )

with col_exp2:
    output = BytesIO()
    with pd.ExcelWriter(output, engine="openpyxl") as writer:
        df_filtrado.to_excel(writer, index=False, sheet_name="Datos Filtrados")
        if col_numericas:
            df_filtrado[col_numericas].describe().to_excel(writer, sheet_name="Estadísticas")
    st.download_button(
        label="⬇️ Descargar como Excel",
        data=output.getvalue(),
        file_name="dashboard_export.xlsx",
        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )

# ─────────────────────────────────────────────
#  FOOTER
# ─────────────────────────────────────────────
st.markdown("""
    <div style='
        text-align:center;
        padding:20px;
        color:#3d4460;
        font-size:12px;
        margin-top:20px;
    '>
        Excel Dashboard Pro · Desarrollado con ❤️ usando Python & Streamlit
    </div>
""", unsafe_allow_html=True)